import type { AuditLog } from '../types/common.types'

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    actor: 'Super Admin',
    actorType: 'admin',
    action: 'Payment Confirmed',
    entity: 'Payment',
    entityId: 'pay-001',
    timestamp: '2025-01-15T09:00:00Z',
    details: 'Confirmed payment for Suresh Patel',
  },
  {
    id: 'audit-002',
    actor: 'Ramesh Yadav',
    actorType: 'district',
    action: 'Driver Approved',
    entity: 'Driver',
    entityId: 'drv-006',
    timestamp: '2025-02-06T10:00:00Z',
    details: 'Approved driver request for Ramesh Chandra',
  },
  {
    id: 'audit-003',
    actor: 'System',
    actorType: 'system',
    action: 'ID Card Generated',
    entity: 'Driver',
    entityId: 'drv-001',
    timestamp: '2024-06-01T12:00:00Z',
    details: 'Auto-generated ID card ADWA-CARD-001',
  },
  {
    id: 'audit-004',
    actor: 'Super Admin',
    actorType: 'admin',
    action: 'District Created',
    entity: 'District',
    entityId: 'd5',
    timestamp: '2024-03-01T08:00:00Z',
    details: 'Added Jaipur district with incharge Ramesh Chandra',
  },
  {
    id: 'audit-005',
    actor: 'Anita Devi',
    actorType: 'district',
    action: 'Payment Collected',
    entity: 'Payment',
    entityId: 'pay-002',
    timestamp: '2025-01-22T11:00:00Z',
    details: 'Collected ₹250 from Anita Devi',
  },
  {
    id: 'audit-006',
    actor: 'Ramesh Yadav',
    actorType: 'district',
    action: 'Driver Rejected',
    entity: 'Driver',
    entityId: 'drv-007',
    timestamp: '2025-01-08T09:00:00Z',
    details: 'Rejected due to invalid license document',
  },
  {
    id: 'audit-007',
    actor: 'Super Admin',
    actorType: 'admin',
    action: 'Notification Created',
    entity: 'Notification',
    entityId: 'notif-001',
    timestamp: '2025-02-01T08:00:00Z',
  },
  {
    id: 'audit-008',
    actor: 'Mohammed Irfan',
    actorType: 'district',
    action: 'Event Created',
    entity: 'Event',
    entityId: 'evt-002',
    timestamp: '2025-02-01T00:00:00Z',
  },
]
