import type { District } from '../types/district.types'

export const mockDistricts: District[] = [
  {
    id: 'd1',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    thanas: ['Hazratganj', 'Gomti Nagar', 'Alambagh', 'Chowk'],
    inchargeName: 'Ramesh Yadav',
    inchargeEmail: 'ramesh.yadav@adwa.org',
    inchargeMobile: '9876543210',
    driverCount: 4520,
    activeRequests: 34,
    status: 'active',
  },
  {
    id: 'd2',
    name: 'Ahmedabad',
    state: 'Gujarat',
    thanas: ['Navrangpura', 'Satellite', 'Maninagar', 'Vastrapur'],
    inchargeName: 'Suresh Patel',
    inchargeEmail: 'suresh.patel@adwa.org',
    inchargeMobile: '9876543211',
    driverCount: 3890,
    activeRequests: 28,
    status: 'active',
  },
  {
    id: 'd3',
    name: 'Mumbai Suburban',
    state: 'Maharashtra',
    thanas: ['Andheri', 'Borivali', 'Kurla', 'Bandra'],
    inchargeName: 'Mohammed Irfan',
    inchargeEmail: 'irfan@adwa.org',
    inchargeMobile: '9876543212',
    driverCount: 6200,
    activeRequests: 45,
    status: 'active',
  },
  {
    id: 'd4',
    name: 'Delhi Central',
    state: 'Delhi',
    thanas: ['Connaught Place', 'Karol Bagh', 'Paharganj', 'Daryaganj'],
    inchargeName: 'Anita Devi',
    inchargeEmail: 'anita@adwa.org',
    inchargeMobile: '9876543213',
    driverCount: 5100,
    activeRequests: 22,
    status: 'active',
  },
  {
    id: 'd5',
    name: 'Jaipur',
    state: 'Rajasthan',
    thanas: ['Malviya Nagar', 'Vaishali Nagar', 'C-Scheme', 'Mansarovar'],
    inchargeName: 'Ramesh Chandra',
    inchargeEmail: 'ramesh.c@adwa.org',
    inchargeMobile: '9876543214',
    driverCount: 2750,
    activeRequests: 15,
    status: 'active',
  },
]
